# Generated by Django 4.1 on 2022-09-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_rename_privacy_text_privacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='privacy',
            field=models.BooleanField(),
        ),
    ]
