# Generated by Django 4.1 on 2022-09-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_temptext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='id',
            field=models.CharField(max_length=500, primary_key=True, serialize=False),
        ),
    ]
