# Generated by Django 4.1 on 2022-09-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_alter_text_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
