# Generated by Django 4.1 on 2022-09-22 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_text_likescount_alter_text_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('img', models.ImageField(default=None, upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='temptext',
            name='txt',
            field=models.CharField(max_length=99999999999999999999999999999999989999999990000000000000000000000000000000001),
        ),
    ]
