# Generated by Django 4.1 on 2022-09-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_img_alter_temptext_txt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='text',
            field=models.CharField(max_length=99999999999999999999999999999999989999999990000000000000000000000000000000001),
        ),
    ]
