# Generated by Django 4.1 on 2022-09-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_alter_text_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='img',
            field=models.ImageField(default='', upload_to='profiles/Imgs'),
        ),
    ]
